const user = {
    displayName: 'Parth',
    email: 'test@test1.com',
    images: [
        {
            format: 'png',
            id: 1,
            name: 'Sample image 1',
            size: '12.2 MB',
            title: 'title1',
            uploadedOn: 'Nov-30-2022',
            url: 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?cs=srgb&dl=pexels-simon-berger-1323550.jpg&fm=jpg',
        },
        {
            format: 'png',
            id: 2,
            name: 'Sample image 2',
            size: '16.2 MB',
            title: 'title2',
            uploadedOn: 'Aug-30-2022',
            url: 'https://images.pexels.com/photos/1631677/pexels-photo-1631677.jpeg?cs=srgb&dl=pexels-abdullah-ghatasheh-1631677.jpg&fm=jpg',
        },
        {
            format: 'jpg',
            id: 3,
            name: 'Sample image 3',
            size: '11.2 MB',
            title: 'title3',
            uploadedOn: 'Jan-30-2022',
            url: 'https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?cs=srgb&dl=pexels-david-besh-884788.jpg&fm=jpg',
        },
        {
            format: 'png',
            id: 4,
            name: 'Sample image 4',
            size: '16.2 MB',
            title: 'title4',
            uploadedOn: 'Aug-30-2022',
            url: 'https://images.pexels.com/photos/1631677/pexels-photo-1631677.jpeg?cs=srgb&dl=pexels-abdullah-ghatasheh-1631677.jpg&fm=jpg',
        },
        {
            format: 'jpg',
            id: 5,
            name: 'Sample image 5',
            size: '11.2 MB',
            title: 'title5',
            uploadedOn: 'Jan-30-2022',
            url: 'https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?cs=srgb&dl=pexels-david-besh-884788.jpg&fm=jpg',
        },
        {
            format: 'png',
            id: 6,
            name: 'Sample image 1',
            size: '12.2 MB',
            title: 'title1',
            uploadedOn: 'Nov-30-2022',
            url: 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?cs=srgb&dl=pexels-simon-berger-1323550.jpg&fm=jpg',
        },
        {
            format: 'png',
            id: 7,
            name: 'Sample image 2',
            size: '16.2 MB',
            title: 'title2',
            uploadedOn: 'Aug-30-2022',
            url: 'https://images.pexels.com/photos/1631677/pexels-photo-1631677.jpeg?cs=srgb&dl=pexels-abdullah-ghatasheh-1631677.jpg&fm=jpg',
        },
        {
            format: 'jpg',
            id: 8,
            name: 'Sample image 3',
            size: '11.2 MB',
            title: 'title3',
            uploadedOn: 'Jan-30-2022',
            url: 'https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?cs=srgb&dl=pexels-david-besh-884788.jpg&fm=jpg',
        },
        {
            format: 'png',
            id: 9,
            name: 'Sample image 4',
            size: '16.2 MB',
            title: 'title4',
            uploadedOn: 'Aug-30-2022',
            url: 'https://images.pexels.com/photos/1631677/pexels-photo-1631677.jpeg?cs=srgb&dl=pexels-abdullah-ghatasheh-1631677.jpg&fm=jpg',
        },
        {
            format: 'jpg',
            id: 10,
            name: 'Sample image 5',
            size: '11.2 MB',
            title: 'title5',
            uploadedOn: 'Jan-30-2022',
            url: 'https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?cs=srgb&dl=pexels-david-besh-884788.jpg&fm=jpg',
        },
    ]
};

export default user;